name.indexOf("change") == -1 && name.indexOf("add") == -1 && name.indexOf("request") == -1 && name.indexOf("sync") == -1 && name.indexOf("fetchQuery") == -1 && name.indexOf("resolved") == -1 && name.indexOf("sort") == -1  && name.indexOf("fetch") == -1  && name.indexOf("scroll") == -1  && name.indexOf("reset") == -1

dev:
  logIn
  showWait
  hideWait
  restartSession
  showWait
  showWait
  hideWait
  sessionLoaded
  connectionStateChanged
  commitCurrentEdit
  commitCurrentEdit
  hideWait
  initialized
  initialized
  route:doHome
  route
  route
  connectionStateChanged
  restartSession
  showWait
  showWait
  hideWait
  sessionLoaded
  connectionStateChanged
  hideWait

introduceflux:
  showWait
  hideWait
  restartSession
  showWait
  showWait
  hideWait
  sessionLoaded
  connectionStateChanged
  hideWait
  commitCurrentEdit
  commitCurrentEdit
  route:doHome
  route
  route
  initialized
  initialized
  selectedRowsChanged
  selectedRowsChanged

introducefluxStash
