embed_assets: off
compress_assets: on
gzip_assets: off

javascripts:
  biscotto:
    - theme/default/lib/scripts/jquery.js
    - theme/default/lib/scripts/keymaster.js
    - theme/default/lib/scripts/underscore.js
    - theme/default/lib/scripts/biscotto.js
    - theme/default/lib/scripts/fuzzy.js
    - theme/default/lib/scripts/highlight.js
    - theme/default/lib/scripts/languages/*.js

stylesheets:
  biscotto:
    - theme/default/lib/styles/*.css
